version: "3.8"

services:
  securityapi:
    build: .
    container_name: securityapi
    ports:
      - target: 8080
        published: 8080
    depends_on:
      - security-db
    links:
      - security-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://security-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  security-db:
    image: postgres:latest
    container_name: security-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres